plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# Configuraciones adicionales para mejorar la calidad del código
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/IfUnlessModifier:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantSort:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/RescueModifier:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringHashKeys:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/YodaCondition:
  Enabled: true

# Configuraciones específicas para Rails
Rails/ApplicationController:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationMailer:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/Date:
  EnforcedStyle: strict

Rails/FilePath:
  EnforcedStyle: arguments

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/LinkToBlank:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/RakeEnvironment:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/ReflectionClassName:
  Enabled: true

Rails/RefuteMethods:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/RequireDependency:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/RootJoinChain:
  Enabled: true

Rails/SafeNavigationWithBlank:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/ScopeArgs:
  Enabled: true

Style/Send:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/Validation:
  Enabled: true
