default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "tpaga_db") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "TPaga.2025.*") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "tpaga_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "tpaga_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "tpaga_production") %>
